### ISSUE TITLE
docker version manual?

### ISSUE THREAD

**Issue by devcomputer** [iudicium/pryingdeep#13]
i run your docker inside an lxc and when I run docker-compose up i see a never ending list of crawls to iana and rfc-editor and so on. no idea how long this is going to take but its quite a while now and I have no idea if this is part of the first start or if need to pass any arguments on start. 
sth. like "go edit pryingdeep.yaml first"?

**Comment by iudicium** [comment]
It's not part of the first start. The crawler finds them as it goes.
Could you share how some of the infinite links look like for e.g iana or rfc-editor.
A quick fix right now would be to add these infinite websites to [dissalowed-domains](https://github.com/iudicium/pryingdeep/blob/main/docs/CONFIG.MD?plain=1#L59) in pryingdeep.yaml

**Comment by fabstest** [comment]
I think he is referring to this one.

![image](https://github.com/iudicium/pryingdeep/assets/153471934/715609b5-e0e6-4542-bf38-173206ea79ff)

**Comment by iudicium** [comment]
> I think he is referring to this one. I encounter the same issue
> 
> ![image](https://private-user-images.githubusercontent.com/153471934/328826513-715609b5-e0e6-4542-bf38-173206ea79ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTQ2NzgsIm5iZiI6MTcxNTI1NDM3OCwicGF0aCI6Ii8xNTM0NzE5MzQvMzI4ODI2NTEzLTcxNTYwOWI1LWUwZTYtNDU0Mi1iZjM4LTE3MzIwNmVhNzlmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMTMyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmYwM2M5NWE2YjBlOTYyMWEyM2Q3OWYwNTE1MTc5ZTZlODhhYmYyODUwNjNiODc3MWEwMTVmYmFjNjAzMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YZ2U6IXh9wmFNBS0E2gZIA8TZy9_q2kxUsp0MdhCBGE)

Oh that happens because the default url in the [config](https://github.com/iudicium/pryingdeep/blob/897211b08568fc7f02795d22fc764cf04ac65148/pryingdeep.yaml#L22)
Is https://example.com
Remove it and it won't go to iana anymore

**Comment by fabstest** [comment]
After removing it I'll just run docker compose up then it'll be fine? Or I still need to rebuild?

**Comment by devcomputer** [comment]
i tried some debian based machines but they all also fail using the docker-compose.yml

![image](https://github.com/iudicium/pryingdeep/assets/35902641/26e0dfdb-02c6-49cf-ae3b-44329d322faf)

**Comment by iudicium** [comment]
> i tried some debian based machines but they all also fail using the docker-compose.yml
> 
> ![image](https://private-user-images.githubusercontent.com/35902641/340716740-26e0dfdb-02c6-49cf-ae3b-44329d322faf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MTE0ODcsIm5iZiI6MTcxODkxMTE4NywicGF0aCI6Ii8zNTkwMjY0MS8zNDA3MTY3NDAtMjZlMGRmZGItMDJjNi00OWNmLWFlM2ItNDQzMjlkMzIyZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzgzODJkMzA2MjZhYTBkNjMwMmYxNTY4MzZkNGNiNWZmZTlhZDFmZjUzYjNlNjFkMDg5ZmRjNzFjZTBlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wi-ExZoumMpXBXXCDpkqC2CNFsFNXuxQgpxu3YMa3PA)
> 
> when I uncomment the healthcheck the containers start and when editing the config to another URL it all just crashed again...but with new errors. ¯_(ツ)_/¯

Maybe there's some issue with the healthcheck that I'm doing [https://github.com/iudicium/pryingdeep/blob/897211b08568fc7f02795d22fc764cf04ac65148/docker-compose.yaml#L10](here). 
Make sure you re-build with the new urls though. I'll try to add some explanation to Docker section within a few days and check the healthcheck.
For now, can you paste the traceback of the new errors here?

**Comment by iudicium** [comment]
Closing due to inacitivity.
